// One-off: turn Natural Earth's 110m land outline into a single SVG path.
//
// Run with `node scripts/build-world.mjs`. The output is committed, so the
// site never fetches map data at runtime and the page stays self-contained.
//
// Source: world-atlas (Natural Earth, public domain).

import { writeFile } from "node:fs/promises";
import { feature } from "topojson-client";

const SRC = "https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json";
const OUT = "src/data/meanwhile/world.ts";

// Equirectangular: longitude and latitude map straight onto x and y. Chosen
// over anything fancier because plotting a country dot is then two lines of
// arithmetic on the client, with no projection library shipped to the browser.
const W = 1000;
const H = 500;
const project = ([lng, lat]) => [
  ((lng + 180) / 360) * W,
  ((90 - lat) / 180) * H,
];

// Antarctica is a projection artefact more than a place here: it smears across
// the whole bottom edge and nobody is visiting from it.
const ANTARCTIC = -60;

const round = (n) => Math.round(n * 10) / 10;

function ring(coords) {
  const pts = coords
    .filter(([, lat]) => lat > ANTARCTIC)
    .map(project)
    .map(([x, y]) => `${round(x)} ${round(y)}`);
  // A sliver of two or three points is noise at this resolution.
  return pts.length < 4 ? "" : `M${pts.join("L")}Z`;
}

const geo = feature(await (await fetch(SRC)).json(), "land");

let d = "";
for (const f of geo.features) {
  const polys = f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates;
  for (const poly of polys) for (const r of poly) d += ring(r);
}

await writeFile(
  OUT,
  `// GENERATED by scripts/build-world.mjs — do not edit by hand.\n` +
    `// Natural Earth 110m land outline (public domain), equirectangular.\n` +
    `export const WORLD_W = ${W};\n` +
    `export const WORLD_H = ${H};\n` +
    `export const WORLD_PATH = ${JSON.stringify(d)};\n`
);

console.log(`world path: ${(d.length / 1024).toFixed(1)} KB`);
